### PR TITLE
Add support to post metrics

### PR DESCRIPTION
**Pull request by renatoaquino**
This small patch adds support to post metrics using datadog's API.
https://docs.datadoghq.com/api/?lang=bash#post-time-series-points

### CODE REVIEW

**Comment by yutannihilation** [comment]
@renatoaquino 
Thanks for your contribution!

Looks good to me. But, unfortunately, since now I've lost my Datadog account due to my job change, I can't verify your implementation is really right.  So, all I can do is to believe in you and to merge this bravely :P Sorry that I can't review enough...

Would you want this to release on CRAN? If so, I will try!

**Comment by renatoaquino** [comment]
Thank you for sharing your code @yutannihilation !!!

I'll be using those changes very soon, and probably will end up adding another API calls. 
If the process to release on CRAN is difficult maybe it could be holded for now.

I'm assured that the changes works, but I'll test them more thoroughly and report my impressions later.

Thank you again.

**Comment by yutannihilation** [comment]
I expect the CRAN process won't be difficult, but I can't submit so frequently as the CRAN policy says:

> Submitting updates should be done responsibly and with respect for the volunteers’ time. Once a package is established (which may take several rounds), “no more than every 1–2 months” seems appropriate.

So, if you have a plan to add more functionalities, I'll wait for it :)

**Comment by yutannihilation** [comment]
@renatoaquino Hi, just a notice, this version is on CRAN now!🎉 (I had to submit this to fix what the CRAN maintainer pointed out)

**Comment by renatoaquino** [comment]
@yutannihilation thank's for letting me know. Just began to really use it this week. If some new necessary changes arrive I'll create a new pull request.

**Pull request merged**
